### ISSUE TITLE
deploy to rinkeby time out

### ISSUE THREAD

**Issue by haoran1062** [PatrickAlphaC/nft-mix#32]
hello, after run `brownie run scripts/advanced_collectible/deploy_advanced.py --network rinkeby`, then output:
```
❯ brownie run scripts/advanced_collectible/deploy_advanced.py --network rinkeby
Brownie v1.16.2 - Python development framework for Ethereum

NftProject is the active project.

Running 'scripts/advanced_collectible/deploy_advanced.py::main'...
rinkeby
Transaction sent: 0x5ab36042e6a5d79afc79953e36cde14dfa0f62b081a99217baab8489b489347c
  Gas price: 1.000000014 gwei   Gas limit: 2546712   Nonce: 8
  AdvancedCollectible.constructor confirmed   Block: 9210887   Gas used: 2315193 (90.91%)
  AdvancedCollectible deployed at: 0x1197Ddf206B0953666C4DF0DC0056cb4b46A5ACA

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f18be0a93d0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-rinkeby.etherscan.io', port=443): Max retries exceeded with url: /api?module=contract&action=getsourcecode&address=0x1197Ddf206B0953666C4DF0DC0056cb4b46A5ACA&apiKey=XPDQDKHGMINTAR1WNDAID5UCBGA141GGMS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f18be0a93d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/haoran/.conda/envs/db/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/haoran/.conda/envs/db/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/brownie/network/contract.py", line 243, in _add_from_tx
    self.at(tx.contract_address, tx.sender, tx)
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/brownie/network/contract.py", line 217, in at
    contract = _find_contract(address)
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/brownie/network/state.py", line 557, in _find_contract
    return Contract(address)
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/brownie/network/contract.py", line 946, in __init__
    contract = self.from_explorer(address, owner=owner, silent=True)
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/brownie/network/contract.py", line 1097, in from_explorer
    data = _fetch_from_explorer(address, "getsourcecode", silent)
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/brownie/network/contract.py", line 1913, in _fetch_from_explorer
    response = requests.get(url, params=params, headers=REQUEST_HEADERS)
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/haoran/.conda/envs/db/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-rinkeby.etherscan.io', port=443): Max retries exceeded with url: /api?module=contract&action=getsourcecode&address=0x1197Ddf206B0953666C4DF0DC0056cb4b46A5ACA&apiKey=XPDQDKHGMINTAR1WNDAID5UCBGA141GGMS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f18be0a93d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

```
I tried many times, but still not work, I do really edited  and `source .env` before run deploy, export my `PRIVATE_KEY` and `WEB3_INFURA_PROJECT_ID`.

**Comment by PatrickAlphaC** [comment]
Hmm.... it looks like the thread is getting killed before it exits. What is the last transaction that you try?

**Comment by Marcuzzz** [comment]
Hi Patrick,

All was working fine now I get this issue:
`ValueError: Gas estimation failed: 'invalid opcode: opcode 0xfe not defined'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.`

No idea what to do to fix it...

(I stil have enough 2.9425 ETH on Rinkeby Test Network)

Also I would like to know how I would send parameters from python script to the contract.
I'm very new to this and trying to wrap my head around it.

Instead of having a enum Breed in the contract I would like to be able to this from the "create_collectible.py" script...
Is that possible?

Cheers

**Comment by PatrickAlphaC** [comment]
Closing due to inactivity, feel free to follow up
