### ISSUE TITLE
ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by jiebanghan** [PatrickAlphaC/nft-mix#85]
Hi, when I run this command below on my PC
source ./.env
brownie run scripts/simple_collectible/deploy_simple.py --network rinkeby
it shows:

```
Brownie v1.17.2 - Python development framework for Ethereum

NftMixMainProject is the active project.

Running 'scripts/advanced_collectible/deploy_advanced.py::main'...
rinkeby
Transaction sent: 0x19422f26575cb61b4b6d1cd29c51694aac68acad94394459eba4424bc0120391
  Gas price: 1.000000012 gwei   Gas limit: 2546712   Nonce: 5
  AdvancedCollectible.constructor confirmed   Block: 10251084   Gas used: 2315193 (90.91%)
  AdvancedCollectible deployed at: 0xd7f2fdc21BC66D7f01469dd33614083b3195b406

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gilsun91/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/gilsun91/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/brownie/network/contract.py", line 256, in _add_from_tx
    self.at(tx.contract_address, tx.sender, tx)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/brownie/network/contract.py", line 230, in at
    contract = _find_contract(address)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/brownie/network/state.py", line 569, in _find_contract
    return Contract(address)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/brownie/network/contract.py", line 875, in __init__
    contract = self.from_explorer(address, owner=owner, silent=True)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/brownie/network/contract.py", line 1026, in from_explorer
    data = _fetch_from_explorer(address, "getsourcecode", silent)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/brownie/network/contract.py", line 1833, in _fetch_from_explorer
    response = requests.get(url, params=params, headers=REQUEST_HEADERS)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/gilsun91/.local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
  File "brownie/_cli/run.py", line 50, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/advanced_collectible/deploy_advanced.py", line 11, in main
    advanced_collectible = AdvancedCollectible.deploy(
  File "brownie/network/contract.py", line 528, in __call__
    return tx["from"].deploy(
  File "brownie/network/account.py", line 555, in deploy
    deployed_contract = contract.at(receipt.contract_address)
  File "brownie/network/contract.py", line 230, in at
    contract = _find_contract(address)
  File "brownie/network/state.py", line 569, in _find_contract
    return Contract(address)
  File "brownie/network/contract.py", line 875, in __init__
    contract = self.from_explorer(address, owner=owner, silent=True)
  File "brownie/network/contract.py", line 1026, in from_explorer
    data = _fetch_from_explorer(address, "getsourcecode", silent)
  File "brownie/network/contract.py", line 1833, in _fetch_from_explorer
    response = requests.get(url, params=params, headers=REQUEST_HEADERS)
  File "requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
how to solve it here ? Thank you very much.

**Comment by PatrickAlphaC** [comment]
This is often an error with an RPC_URL.

Are you using alchemy or infura?

**Comment by jiebanghan** [comment]
I have used infura and registered it. I  have used the project id from the infura. So what is your suggestion about my question? thank you very much.

**Comment by wlgc1801lzh** [comment]
I have the same problem. How can I solve it?

**Comment by PatrickAlphaC** [comment]
Please use [alchemy](https://alchemy.com/?a=673c802981)
